### ISSUE TITLE
Octokit::BadGateway

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#105]
In production a few hours ago

```
Octokit::BadGateway: GET https://api.github.com/user/repository_invitations: 502 - Server Error
  from octokit/response/raise_error.rb:16:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:61:in `on_complete'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/rack_builder.rb:141:in `build_response'
  from faraday/connection.rb:386:in `run_request'
  from faraday/connection.rb:149:in `get'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:84:in `paginate'
  from octokit/client/repository_invitations.rb:72:in `user_repository_invitations'
  from 0pdd.rb:173:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

I think we need to retry in this case. Or let's think about something smarter.

**Comment by yegor256** [comment]
@0crat assign @tedtoer

**Comment by 0crat** [comment]
> @0crat assign @tedtoer  ([here](https://github.com/yegor256/0pdd/issues/105#issuecomment-336804180))

@yegor256 Job `gh:yegor256/0pdd#105` assigned to @tedtoer, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4040](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@tedtoer this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#105`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#105` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#105` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#105` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#105` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#105` assigned to @tedtoer. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#105`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#105` assigned to @tedtoer  ([profile](http://www.0crat.com/u/tedtoer})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by SilasReinagel** [comment]
An HTTP 502 error is a transient error. https://tools.ietf.org/html/rfc7231#section-6.6.3
This is not a problem with 0pdd. Bug should be closed.

**Comment by SilasReinagel** [comment]
@yegor256 This ticket needs your attention. Probably should be closed.

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SilasReinagel** [comment]
@yegor256 This ticket needs your attention. Close this unless you have reproduction steps and this is a regular recurring error.

**Comment by yegor256** [comment]
@SilasReinagel don't you like the idea of retrying in case of 50x?

**Comment by 0crat** [comment]
@izrik[/z](https://www.0crat.com/u/izrik) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by izrik** [comment]
@0crat status

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/0pdd/issues/105) assigned to @dmydlarz[/z](https://www.0crat.com/u/dmydlarz), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1301158878); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by yegor256** [comment]
@0crat status

**Comment by yegor256** [comment]
@dmydlarz we are experiencing this issue now. What is the status?

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/0pdd/issues/105#issuecomment-382608813))

@izrik This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#105](https://github.com/yegor256/0pdd/issues/105) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @tedtoer[/z](https://www.0crat.com/u/tedtoer): User was resigned from the ticket
    * @valentjedi[/z](https://www.0crat.com/u/valentjedi): User was resigned from the ticket
    * @prondzyn[/z](https://www.0crat.com/u/prondzyn): User was resigned from the ticket
    * @vl3[/z](https://www.0crat.com/u/vl3): User was resigned from the ticket
    * @silasreinagel[/z](https://www.0crat.com/u/silasreinagel): User was resigned from the ticket
    * @izrik[/z](https://www.0crat.com/u/izrik): User was resigned from the ticket
    * @dmydlarz[/z](https://www.0crat.com/u/dmydlarz): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T46CUJJ?q=%7Bjob%3A%27gh%3Ayegor256%2F0pdd%23105%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/0pdd/issues/105#issuecomment-393133971))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#105](https://github.com/yegor256/0pdd/issues/105) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @tedtoer[/z](https://www.0crat.com/u/tedtoer): User was resigned from the ticket
    * @valentjedi[/z](https://www.0crat.com/u/valentjedi): User was resigned from the ticket
    * @prondzyn[/z](https://www.0crat.com/u/prondzyn): User was resigned from the ticket
    * @vl3[/z](https://www.0crat.com/u/vl3): User was resigned from the ticket
    * @silasreinagel[/z](https://www.0crat.com/u/silasreinagel): User was resigned from the ticket
    * @izrik[/z](https://www.0crat.com/u/izrik): User was resigned from the ticket
    * @dmydlarz[/z](https://www.0crat.com/u/dmydlarz): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T46CUJJ?q=%7Bjob%3A%27gh%3Ayegor256%2F0pdd%23105%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/0pdd/issues/105) assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1750831156); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by golyalpha** [comment]
@yegor256 502 usually means the server was under high load and the proxy had no endpoint to forward your request to at the moment, that the backend was down for some reason or that there was an error in configuration causing the gateway/proxy server being unable to access the upstream server that would normally handle the request and build the dynamic page.

While under certain circumstances, retrying x times in succession might help, but in most cases, it won't.

Need a proposal on how to handle this if I'm going to write some code for this issue.

**Comment by yegor256** [comment]
@golyalpha what would you propose?

**Comment by golyalpha** [comment]
@yegor256 Well, if creating an issue with the puzzle on a GitHub repo is a problem, I'd probably put any failed issue creation requests into some kind of a queue (maybe as an entry in the DB), and then, once an issue creation request succeeds, I'd flush the queue onto GitHub as well. Maybe sprinkle in some longer-term retries, for example, if a new issue creation request wasn't made in the past hour, retry one of the requests in the queue.

**Comment by yegor256** [comment]
@golyalpha let's go with a simple in-memory queue, which will simply help us retry requests in, say, 15 minutes.

**Comment by golyalpha** [comment]
@yegor256 0pdd is hosted on Heroku, isn't it? If it is, it means that the service gets restarted roughly every 24 hours. Some requests may end up getting unlucky and lost completely if the service restarts while they are in the queue. 
Of course, if you insist on having the queue in memory (which, admittedly, is the simplest and fastest to access), then I'll do it that way.

**Comment by yegor256** [comment]
@golyalpha I don't insist. You think it's better to keep it in DynamoDB?

**Comment by golyalpha** [comment]
@yegor256 I'm not entirely sure. How often do these errors happen? (If not very often, then RAM might be better choice)

**Comment by yegor256** [comment]
@golyalpha not very often, maybe once a week or so

**Comment by 0crat** [comment]
@golyalpha[/z](https://www.0crat.com/u/golyalpha) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
> @0crat resign Won't be able to finish in time. ([here](https://github.com/yegor256/0pdd/issues/105#issuecomment-402037048))

@golyalpha The user @golyalpha[/z](https://www.0crat.com/u/golyalpha) resigned from [#105](https://github.com/yegor256/0pdd/issues/105), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @golyalpha[/z](https://www.0crat.com/u/golyalpha)

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/0pdd/issues/105) assigned to @timeracers[/z](https://www.0crat.com/u/timeracers), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1871122771); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@timeracers[/z](https://www.0crat.com/u/timeracers) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by timeracers** [comment]
@0crat wait for #228

**Comment by 0crat** [comment]
> @0crat wait for #228 ([here](https://github.com/yegor256/0pdd/issues/105#issuecomment-404393528))

@timeracers The impediment for [#105](https://github.com/yegor256/0pdd/issues/105) was registered successfully by @timeracers[/z](https://www.0crat.com/u/timeracers)

**Comment by 0crat** [comment]
> @0crat wait for #228  ([here](https://github.com/yegor256/0pdd/issues/105#issuecomment-404394516))

@timeracers Job [#105](https://github.com/yegor256/0pdd/issues/105) is already on hold
