### ISSUE TITLE
log: undefined local variable or method `user' for #

### ISSUE THREAD

**Issue by fxnn** [yegor256/0pdd#117]
The page [`http://www.0pdd.com/log?name=fxnn/deadbox`](http://www.0pdd.com/log?name=fxnn/deadbox) currently shows an internal error:

```
Internal error

Please help us improve our service and submit the following stacktrace to our issue tracker in GitHub: yegor256/0pdd

undefined local variable or method `user' for #
	/app/views/log.haml:1:in `block in singleton class'
	/app/views/log.haml:-7:in `instance_eval'
	/app/views/log.haml:-7:in `singleton class'
	/app/views/log.haml:-10:in `__tilt_69811674659440'
	/app/vendor/bundle/ruby/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
	/app/vendor/bundle/ruby/2.3.0/gems/tilt-2.0.8/lib/tilt/haml.rb:24:in `evaluate'
	/app/vendor/bundle/ruby/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:839:in `render'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:692:in `haml'
	/app/0pdd.rb:202:in `block in '
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fxnn** [comment]
Problem also exists for other GitHub repos, e.g. [`http://www.0pdd.com/log?name=kkamkou/gitmostwanted.com`](http://www.0pdd.com/log?name=kkamkou/gitmostwanted.com). No problem for e.g. the `name` page, see [`http://www.0pdd.com/p?name=fxnn/deadbox`](http://www.0pdd.com/p?name=fxnn/deadbox).

**Comment by yegor256** [comment]
@fxnn please, check now, I believe it's fixed.

**Comment by fxnn** [comment]
@yegor256 Confirmed! Thank you.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#117` was not in scope
