### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#120]
https://sentry.io/zerocracy/0pdd/issues/356005491/

```
TypeError: no implicit conversion of nil into String
  0pdd.rb:406:in `join'
    File.join('/tmp/0pdd-xml-cache', repo)
  0pdd.rb:406:in `storage'
    File.join('/tmp/0pdd-xml-cache', repo)
  0pdd.rb:240:in `block in <top (required)>'
    storage(name).load, ['project', "'#{name}'"]
  sinatra/base.rb:1632:in `call'
    proc { |a, p| unbound_method.bind(a).call }
  sinatra/base.rb:1632:in `block in compile!'
    proc { |a, p| unbound_method.bind(a).call }
...
(41 additional frame(s) were not displayed)

TypeError: no implicit conversion of nil into String
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.2`

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#120` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3555](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#120` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3585](http://www.0crat.com/u/yegor256).
