### ISSUE TITLE
RuntimeError: set -x;set -e;set -o pipefail;cd /tmp/0pdd20170922-4-grthfi/pivot-libre/tideman && git reset --ha...

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#121]
https://sentry.io/zerocracy/0pdd/issues/354479117/

```
RuntimeError: set -x;set -e;set -o pipefail;cd /tmp/0pdd20170922-4-grthfi/pivot-libre/tideman && git reset --hard --quiet && git clean --force -d && git fetch --quiet && git checkout master && git rebase --abort || true && git rebase --strategy-option=theirs origin/master: pid 14017 exit 1 (not zero):
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20170922-4-grthfi/pivot-libre/tideman
+ git reset --hard --quiet
+ git clean --force -d
+ git fetch --quiet
+ git checkout master
error: pathspec 'master' did not match any file(s) known to git.
+ true
+ git rebase --strategy-option=theirs origin/master
fatal: Needed a single revision
invalid upstream origin/master


  objects/exec.rb:41:in `block in run'
    raise "#{c}: #{thr.value} (not zero):\n#{stderr.read}\n#{stdout.read}"
  open3.rb:205:in `popen_run'
    return yield(*result)
  open3.rb:95:in `popen3'
    popen_run(cmd, opts, [in_r, out_w, err_w], [in_w, out_r, err_r], &block)
  objects/exec.rb:39:in `run'
    Open3.popen3('bash', '-c', c) do |_, stdout, stderr, thr|
  objects/git_repo.rb:97:in `pull'
    ).run
...
(45 additional frame(s) were not displayed)

RuntimeError: set -x;set -e;set -o pipefail;cd /tmp/0pdd20170922-4-grthfi/pivot-libre/tideman && git reset --hard --quiet && git clean --force -d && git fetch --quiet && git checkout master && git rebase --abort || true && git rebase --strategy-option=theirs origin/master: pid 14017 exit 1 (not zero):
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20170922-4-grthfi/pivot-libre/tideman
+ git reset --hard --quiet
+ git clean --force -d
+ git fetch --quiet
+ git checkout master
error: pathspec 'master' did not match any file(s) known to git.
+ true
+ git rebase --strategy-option=theirs origin/master
fatal: Needed a single revision
invalid upstream origin/master


```

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#121` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3540](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#121` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3615](http://www.0crat.com/u/yegor256).
