### ISSUE TITLE
RuntimeError: set -x;set -e;set -o pipefail;git clone --depth=1 git@github.com:teamed/yegor256/tacit /tmp/0pdd2...

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#122]
https://sentry.io/zerocracy/0pdd/issues/354344791/

```
RuntimeError: set -x;set -e;set -o pipefail;git clone --depth=1 git@github.com:teamed/yegor256/tacit /tmp/0pdd20170929-4-fgwkpf/teamed/yegor256/tacit --quiet: pid 10289 exit 128 (not zero):
+ set -e
+ set -o pipefail
+ git clone --depth=1 git@github.com:teamed/yegor256/tacit /tmp/0pdd20170929-4-fgwkpf/teamed/yegor256/tacit --quiet
fatal: remote error: 
  teamed/yegor256/tacit is not a valid repository name
  Email support@github.com for help


  objects/exec.rb:41:in `block in run'
    raise "#{c}: #{thr.value} (not zero):\n#{stderr.read}\n#{stdout.read}"
  open3.rb:205:in `popen_run'
    return yield(*result)
  open3.rb:95:in `popen3'
    popen_run(cmd, opts, [in_r, out_w, err_w], [in_w, out_r, err_r], &block)
  objects/exec.rb:39:in `run'
    Open3.popen3('bash', '-c', c) do |_, stdout, stderr, thr|
  objects/git_repo.rb:81:in `clone'
    ).run
...
(45 additional frame(s) were not displayed)

RuntimeError: set -x;set -e;set -o pipefail;git clone --depth=1 git@github.com:teamed/yegor256/tacit /tmp/0pdd20170929-4-fgwkpf/teamed/yegor256/tacit --quiet: pid 10289 exit 128 (not zero):
+ set -e
+ set -o pipefail
+ git clone --depth=1 git@github.com:teamed/yegor256/tacit /tmp/0pdd20170929-4-fgwkpf/teamed/yegor256/tacit --quiet
fatal: remote error: 
  teamed/yegor256/tacit is not a valid repository name
  Email support@github.com for help


```

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.4`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#122` was not in scope
