### ISSUE TITLE
Octokit::NotFound: GET https://api.github.com/repos/extsoft/insight: 404 - Not Found // See: https://developer.githu...

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#128]
https://sentry.io/zerocracy/0pdd/issues/362698976/

```
Octokit::NotFound: GET https://api.github.com/repos/extsoft/insight: 404 - Not Found // See: https://developer.github.com/v3
  octokit/response/raise_error.rb:16:in `on_complete'
    raise error
  faraday/response.rb:9:in `block in call'
    on_complete(environment)
  faraday/response.rb:61:in `on_complete'
    yield(env)
  faraday/response.rb:8:in `call'
    @app.call(env).on_complete do |environment|
  octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    response = @app.call(env)
...
(53 additional frame(s) were not displayed)

Octokit::NotFound: GET https://api.github.com/repos/extsoft/insight: 404 - Not Found // See: https://developer.github.com/v3
```

Full:

```
Octokit::NotFound: GET https://api.github.com/repos/extsoft/insight: 404 - Not Found // See: https://developer.github.com/v3
  from octokit/response/raise_error.rb:16:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:61:in `on_complete'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/rack_builder.rb:141:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:137:in `get'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:19:in `get'
  from octokit/client/repositories.rb:29:in `repository'
  from 0pdd.rb:388:in `repo'
  from 0pdd.rb:208:in `block in <top (required)>'
  from sinatra/base.rb:1632:in `call'
  from sinatra/base.rb:1632:in `block in compile!'
  from sinatra/base.rb:991:in `block (3 levels) in route!'
  from sinatra/base.rb:1010:in `route_eval'
  from sinatra/base.rb:991:in `block (2 levels) in route!'
  from sinatra/base.rb:1037:in `block in process_route'
  from sinatra/base.rb:1035:in `catch'
  from sinatra/base.rb:1035:in `process_route'
  from sinatra/base.rb:989:in `block in route!'
  from sinatra/base.rb:988:in `each'
  from sinatra/base.rb:988:in `route!'
  from sinatra/base.rb:1094:in `block in dispatch!'
  from sinatra/base.rb:1073:in `block in invoke'
  from sinatra/base.rb:1073:in `catch'
  from sinatra/base.rb:1073:in `invoke'
  from sinatra/base.rb:1091:in `dispatch!'
  from sinatra/base.rb:923:in `block in call!'
  from sinatra/base.rb:1073:in `block in invoke'
  from sinatra/base.rb:1073:in `catch'
  from sinatra/base.rb:1073:in `invoke'
  from sinatra/base.rb:923:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1955:in `call'
  from sinatra/base.rb:1499:in `block in call'
  from sinatra/base.rb:1726:in `synchronize'
  from sinatra/base.rb:1499:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@irbuch can you take care of this one? It seems to be not so complex and can be solved in one pull request (I hope).

**Comment by yegor256** [comment]
@0crat assign @irbuch

**Comment by 0crat** [comment]
> @0crat assign @irbuch ([here](https://github.com/yegor256/0pdd/issues/128#issuecomment-335041014))

@yegor256 Job `gh:yegor256/0pdd#128` assigned to @irbuch, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @irbuch is not a member of this project yet, but can request to join. @irbuch check your [Zerocracy profile](http://www.0crat.com/u/irbuch) and follow the instructions.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+3740](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/0pdd/issues/128#issuecomment-335237438))

@yegor256 @irbuch resigned from `gh:yegor256/0pdd#128`, please stop working.

**Comment by tedtoer** [comment]
Octokit gets 404 error, It means that octokit has not access to this private repo
It might be in 2 cases:
1) Auth code is broken
2) Repo author did not get access for 0pdd

**Comment by yegor256** [comment]
@tedtoer yes, in either case we should handle this situation correctly. Instead of showing this exception to the user, let's render the page right.

@tedtoer please, don't forget to start your message with the name of the person you're talking to. Otherwise, I just miss your messages.

**Comment by tedtoer** [comment]
@yegor256 yes, I'll try to fix it with render the error page instead of showing exception

**Comment by yegor256** [comment]
@tedtoer great, thanks. First, make sure you can reproduce the problem with a unit test. Then, fix it. Then, send a pull request for review.

**Comment by tedtoer** [comment]
@yegor256 I sent PR, please check out

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#128` is now out of scope.

**Comment by yegor256** [comment]
@tedtoer thanks!
