### ISSUE TITLE
535 Authentication Credentials Invalid

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#131]
```
535 Authentication Credentials Invalid

/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/smtp.rb:977:in `check_auth_response'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/smtp.rb:741:in `auth_plain'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/smtp.rb:733:in `authenticate'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/smtp.rb:568:in `do_start'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.6/lib/mail/network/delivery_methods/smtp.rb:111:in `deliver!'
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.6/lib/mail/message.rb:253:in `deliver!'
/app/objects/job_emailed.rb:68:in `block in proceed'
/app/objects/job_emailed.rb:41:in `each'
/app/objects/job_emailed.rb:41:in `rescue in proceed'
/app/objects/job_emailed.rb:34:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:49:in `block in exclusive'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/app/objects/job_detached.rb:47:in `exclusive'
/app/objects/job_detached.rb:37:in `block in proceed'
/app/objects/job_detached.rb:37:in `fork'
/app/objects/job_detached.rb:37:in `proceed'
/app/0pdd.rb:336:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `b
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.8`

**Comment by DronMDF** [comment]
@yegor256 Thanks.

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.9`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#131` was not in scope
