### ISSUE TITLE
deps are outdated

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#133]
See https://gemnasium.com/yegor256/0pdd

Let's upgrade them. Also, can we make sure that `rake` fails if some dependencies are outdated? That would be the best solution.

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #133 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnUnassign.react(RbOnUnassign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback...
```

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#133` is in scope.

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #133 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnUnassign.react(RbOnUnassign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback...
```

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#133` assigned to @0crat, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @0crat is not a member of this project yet, but can request to join. @0crat check your [Zerocracy profile](http://www.0crat.com/u/0crat) and follow the instructions.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+3985](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#133` is already in scope

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/0pdd/issues/133#issuecomment-336096901))

@yegor256 @0crat resigned from `gh:yegor256/0pdd#133`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#133` assigned to @tedtoer, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#133`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#133` is not assigned, can't get performer

**Comment by 0crat** [comment]
@tedtoer this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#133`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#133` is not assigned to anyone.

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#133`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#133` assigned to @tedtoer  ([profile](http://www.0crat.com/u/tedtoer})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#133`, please stop working.

**Comment by vl3** [comment]
I just got -30 points for this task but it was already merged. Why was that? 
Thanks !

**Comment by 0crat** [comment]
The job [#133](https://github.com/yegor256/0pdd/issues/133) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/921723977); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by SilasReinagel** [comment]
@0crat waiting #187

**Comment by 0crat** [comment]
> @0crat waiting #187  ([here](https://github.com/yegor256/0pdd/issues/133#issuecomment-378438908))

@SilasReinagel The impediment for [#133](https://github.com/yegor256/0pdd/issues/133) was registered successfully by @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by SilasReinagel** [comment]
@yegor256 Am I supposed to get 0crat points for completing this task? I don't see them.

**Comment by yegor256** [comment]
@SilasReinagel that's because rultor closed it by mistake.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
The job [#133](https://github.com/yegor256/0pdd/issues/133) is now out of scope
