### ISSUE TITLE
`wait_readable': execution expired (Timeout::Error)

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#137]
Can't close issues (none of them): 

```
2017-10-25T13:28:28.085738+00:00 app[web.1]: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable': execution expired (Timeout::Error)
2017-10-25T13:28:28.085750+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
2017-10-25T13:28:28.085751+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
2017-10-25T13:28:28.085796+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
2017-10-25T13:28:28.085798+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
2017-10-25T13:28:28.085799+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
2017-10-25T13:28:28.085800+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/net_http/patches.rb:30:in `block in new_transport_request'
2017-10-25T13:28:28.085804+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/net_http/patches.rb:27:in `catch'
2017-10-25T13:28:28.085805+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/net_http/patches.rb:27:in `new_transport_request'
2017-10-25T13:28:28.085806+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1407:in `request'
2017-10-25T13:28:28.085806+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
2017-10-25T13:28:28.085807+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
2017-10-25T13:28:28.085808+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
2017-10-25T13:28:28.085810+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1156:in `get'
2017-10-25T13:28:28.085811+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
2017-10-25T13:28:28.085812+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
2017-10-25T13:28:28.085814+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
2017-10-25T13:28:28.085815+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
2017-10-25T13:28:28.085817+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
2017-10-25T13:28:28.085819+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
2017-10-25T13:28:28.085821+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
2017-10-25T13:28:28.085823+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
2017-10-25T13:28:28.085847+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
2017-10-25T13:28:28.085848+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
2017-10-25T13:28:28.085849+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
2017-10-25T13:28:28.085852+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
2017-10-25T13:28:28.085852+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
2017-10-25T13:28:28.085853+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:19:in `get'
2017-10-25T13:28:28.085855+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/client/issues.rb:114:in `issue'
2017-10-25T13:28:28.085857+00:00 app[web.1]: 	from /app/objects/github_tickets.rb:73:in `close'
2017-10-25T13:28:28.085864+00:00 app[web.1]: 	from /app/objects/logged_tickets.rb:55:in `close'
2017-10-25T13:28:28.085866+00:00 app[web.1]: 	from /app/objects/commit_tickets.rb:45:in `close'
2017-10-25T13:28:28.085871+00:00 app[web.1]: 	from /app/objects/emailed_tickets.rb:59:in `close'
2017-10-25T13:28:28.085873+00:00 app[web.1]: 	from /app/objects/safe_tickets.rb:39:in `close'
2017-10-25T13:28:28.085878+00:00 app[web.1]: 	from /app/objects/puzzles.rb:77:in `block in expose'
2017-10-25T13:28:28.085881+00:00 app[web.1]: 	from /app/objects/puzzles.rb:69:in `loop'
2017-10-25T13:28:28.085883+00:00 app[web.1]: 	from /app/objects/puzzles.rb:69:in `expose'
2017-10-25T13:28:28.085889+00:00 app[web.1]: 	from /app/objects/puzzles.rb:34:in `deploy'
2017-10-25T13:28:28.085891+00:00 app[web.1]: 	from /app/objects/job.rb:40:in `proceed'
2017-10-25T13:28:28.085892+00:00 app[web.1]: 	from /app/objects/job_starred.rb:33:in `proceed'
2017-10-25T13:28:28.085910+00:00 app[web.1]: 	from /app/objects/job_recorded.rb:32:in `proceed'
2017-10-25T13:28:28.085911+00:00 app[web.1]: 	from /app/objects/job_emailed.rb:35:in `proceed'
2017-10-25T13:28:28.085911+00:00 app[web.1]: 	from /app/objects/job_commiterrors.rb:36:in `proceed'
2017-10-25T13:28:28.085914+00:00 app[web.1]: 	from /app/objects/job_detached.rb:49:in `block in exclusive'
2017-10-25T13:28:28.085914+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
2017-10-25T13:28:28.085916+00:00 app[web.1]: 	from /app/objects/job_detached.rb:47:in `exclusive'
2017-10-25T13:28:28.085918+00:00 app[web.1]: 	from /app/objects/job_detached.rb:37:in `block in proceed'
2017-10-25T13:28:28.085920+00:00 app[web.1]: 	from /app/objects/job_detached.rb:37:in `fork'
2017-10-25T13:28:28.085922+00:00 app[web.1]: 	from /app/objects/job_detached.rb:37:in `proceed'
2017-10-25T13:28:28.085928+00:00 app[web.1]: 	from /app/0pdd.rb:347:in `block in <top (required)>'
2017-10-25T13:28:28.085930+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
2017-10-25T13:28:28.085952+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
2017-10-25T13:28:28.085953+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
2017-10-25T13:28:28.085954+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
2017-10-25T13:28:28.085957+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
2017-10-25T13:28:28.085957+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
2017-10-25T13:28:28.085958+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
2017-10-25T13:28:28.085960+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
2017-10-25T13:28:28.085962+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
2017-10-25T13:28:28.085964+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
2017-10-25T13:28:28.085966+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
2017-10-25T13:28:28.085968+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
2017-10-25T13:28:28.085969+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
2017-10-25T13:28:28.085976+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
2017-10-25T13:28:28.085978+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
2017-10-25T13:28:28.085980+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
2017-10-25T13:28:28.085981+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
2017-10-25T13:28:28.085987+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
2017-10-25T13:28:28.085989+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
2017-10-25T13:28:28.085991+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
2017-10-25T13:28:28.085993+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
2017-10-25T13:28:28.085999+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
2017-10-25T13:28:28.086001+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
2017-10-25T13:28:28.086003+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
2017-10-25T13:28:28.086005+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
2017-10-25T13:28:28.086011+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
2017-10-25T13:28:28.086013+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
2017-10-25T13:28:28.086014+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
2017-10-25T13:28:28.086016+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
2017-10-25T13:28:28.086041+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
2017-10-25T13:28:28.086042+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
2017-10-25T13:28:28.086043+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
2017-10-25T13:28:28.086045+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
2017-10-25T13:28:28.086046+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-10-25T13:28:28.086050+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
2017-10-25T13:28:28.086052+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
2017-10-25T13:28:28.086053+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
2017-10-25T13:28:28.086054+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
2017-10-25T13:28:28.086056+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
2017-10-25T13:28:28.086057+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
2017-10-25T13:28:28.086058+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
2017-10-25T13:28:28.086060+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
2017-10-25T13:28:28.086062+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:2
```

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#137`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#137` is not in scope.
