### ISSUE TITLE
RuntimeError: XML has 1 errors

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#140]
https://sentry.io/zerocracy/0pdd-j0/issues/399937148/

```
RuntimeError: XML has 1 errors
w2:0: ERROR: Element '{puzzles.xsd}puzzles': No matching global declaration available for the validation root.
<?xml version="1.0"?>
<puzzles xmlns="puzzles.xsd" xsi:noNamespaceSchemaLocation="http://www.0pdd.com/puzzles.xsd"/>

  objects/safe_storage.rb:45:in `valid'
    raise "XML has #{errors.length} errors\nw#{errors.join("\n")}\n#{xml}"
  objects/safe_storage.rb:37:in `save'
    @origin.save(valid(xml))
  objects/upgraded_storage.rb:47:in `save'
    @origin.save(xml)
  objects/upgraded_storage.rb:41:in `load'
    save(xml)
  0pdd.rb:245:in `block in <top (required)>'
    storage(name).load, ['project', "'#{name}'"]
...
(43 additional frame(s) were not displayed)

RuntimeError: XML has 1 errors
w2:0: ERROR: Element '{puzzles.xsd}puzzles': No matching global declaration available for the validation root.
<?xml version="1.0"?>
<puzzles xmlns="puzzles.xsd" xsi:noNamespaceSchemaLocation="http://www.0pdd.com/puzzles.xsd"/>

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.5`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#140`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#140` is not in scope.
