### ISSUE TITLE
breaks XML on submit

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#142]
```
XML has 2 errors
w1:0: ERROR: Element 'issue': [facet 'pattern'] The value '' is not accepted by the pattern '[0-9]+|[A-Z]+-[0-9]+|unknown'.
1:0: ERROR: Element 'issue': '' is not a valid value of the atomic type 'issue_name'.
<?xml version="1.0"?>
<puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.0pdd.com/puzzles.xsd" date="2017-11-06T16:16:25+00:00" version="0.25.6">

<puzzle alive="true">
    <ticket>274</ticket>
    <estimate>0</estimate>
    <role>IMP</role>
    <id>274-d99b4650</id>
    <lines>17-18</lines>
    <body>Split magma::Key to magma::Forward and magma::Backward? need to think about it.</body>
    <file>magma/Key.h</file>
    <author>Andrey Valyaev</author>
    <email>dron.valyaev@gmail.com</email>
    <time>2017-10-04T20:53:42Z</time>
    <children/>
    <issue href=""/>
  </puzzle>

/app/objects/safe_storage.rb:45:in `valid'
/app/objects/safe_storage.rb:37:in `save'
/app/objects/upgraded_storage.rb:47:in `save'
/app/objects/puzzles.rb:47:in `save'
/app/objects/puzzles.rb:98:in `block in expose'
/app/objects/puzzles.rb:83:in `loop'
/app/objects/puzzles.rb:83:in `expose'
/app/objects/puzzles.rb:34:in `deploy'
/app/objects/job.rb:36:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:35:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:49:in `block in exclusive'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/app/objects/job_detached.rb:47:in `exclusive'
/app/objects/job_detached.rb:37:in `block in proceed'
/app/objects/job_detached.rb:37:in `fork'
/app/objects/job_detached.rb:37:in `proceed'
/app/0pdd.rb:342:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.7`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#142`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#142` is not in scope.
