### ISSUE TITLE
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#167]
https://sentry.io/zerocracy/0pdd-j0/issues/371237692/

```
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
  octokit/repository.rb:90:in `raise_invalid_repository!'
    raise Octokit::InvalidRepository, "Invalid Repository. Use user/repo format."
  octokit/repository.rb:34:in `initialize'
    raise_invalid_repository!
  octokit/repository.rb:58:in `new'
    new(repo).path
  octokit/repository.rb:58:in `path'
    new(repo).path
  octokit/client/repositories.rb:29:in `repository'
    get Repository.path(repo), options
...
(45 additional frame(s) were not displayed)

Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.12`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#167`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#167` is not in scope.
