### ISSUE TITLE
[regression] Complains to commented lines in the XML file

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#168]
I've just faced the following error:

> ERROR: src/main/config/checkstyle.xml; puzzle at line #265; @todo must have a leading space to become a puzzle, as this page explains: https://github.com/yegor256/pdd#how-to-format. If you can't understand the cause of this issue or you don't know how to fix it, please submit a GitHub issue, we will try to help you: https://github.com/yegor256/pdd/issues. This tool is still in its beta version and we will appreciate your feedback. Here is where you can find more documentation: https://github.com/yegor256/pdd/blob/master/README.md.

The full log is here: https://github.com/php-coder/mystamps/commit/ecfdd3c17d3e9968cca882fd899a43d8bdbe5f99#commitcomment-26226287

It complains to the following lines:

https://github.com/php-coder/mystamps/blob/ecfdd3c17d3e9968cca882fd899a43d8bdbe5f99/src/main/config/checkstyle.xml#L260-L268

Because it wasn't here before, I'm interesting to know: is it expected new behavior or rather a bug?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder it's expected. Replace `@` with `&#x40;`

**Comment by php-coder** [comment]
Ok, thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#168`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#168` is not in scope.
