### ISSUE TITLE
Cannot run 0pdd on Windows

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/0pdd#193]
Running Windows 10, x64, with Ruby 2.3.3 installed.

When trying to run 0pdd.rb the following error occurs:

```
D:/srcctrl/0pdd-dev/0pdd.rb:81:in `initialize': No such file or directory @ rb_sysopen - D:/srcctrl/0pdd-dev/config.yml (Errno::ENOENT)
	from D:/srcctrl/0pdd-dev/0pdd.rb:81:in `open'
	from D:/srcctrl/0pdd-dev/0pdd.rb:81:in `block in <top (required)>'
	from D:/Languages/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1425:in `configure'
	from D:/Languages/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1925:in `block (2 levels) in delegate'
	from D:/srcctrl/0pdd-dev/0pdd.rb:60:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
I found the documentation for how to setup correctly.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
