### ISSUE TITLE
0pdd stopped working on my private repository

### ISSUE THREAD

**Issue by StuporHero** [yegor256/0pdd#204]
I setup a repository at sunsofterp/phoenix to test out using 0pdd with a data modeling tool which saves its state as XML files. I added 0pdd as a contributor, added the webhook to reHTTP url, and configured the repository with the attached `.0pdd.yml` file. I added a `@todo` comment on one of the tables in the model. I received an error message as expected because I did not format my `@todo` comment properly. I messed it up one more time and received an error message. When I got the format correct, I stopped receiving error notifications, but I do not have any reported issues on my repository. I would like it to report new issues from my `@todo`s.

Here is the response from the latest delivery over the webhook:

Headers
```
Connection: keep-alive
Content-Length: 25
Content-Type: text/html;charset=utf-8
Date: Sat, 12 May 2018 18:13:12 GMT
Server: WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21)
Vary: Cookie
Via: 1.1 vegur, 1.1 vegur
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Rehttp-Revision: BUILD
X-Takes-Millis: 344
X-Takes-Tkproxy: from /hook/github to http://www.0pdd.com/hook/github by org.takes.tk.TkProxy
X-Takes-Version: 1.11.3 137ea65 2018-04-02T14:31:25
X-Xss-Protection: 1; mode=block
```
Body
```
Thanks sunsofterp/phoenix
```
(Given the txt extension so GitHub would accept it.)
[.0pdd.yml.txt](https://github.com/yegor256/0pdd/files/1997857/default.0pdd.yml.txt)

Thanks in advance for your help!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@stuporhero[/z](https://www.0crat.com/u/stuporhero) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by StuporHero** [comment]
It just occurred to me that the `@todo `body text is followed by a closing xml tag which is being included in the text. It appears to be getting escaped on a manual run of pdd, so I don't know if that actually matters. Here is a gist of the manual pdd outbput: [pdd-output.xml](https://gist.github.com/StuporHero/2152b3eacf6fe09f932e671f25f27c91)

**Comment by yegor256** [comment]
@StuporHero sounds weird... Do you see the puzzle here: http://www.0pdd.com/p?name=sunsofterp/phoenix ?

**Comment by yegor256** [comment]
@StuporHero it seems that 0pdd GitHub user can't access your repo. This is my best guess. Are you sure it is in the list of contributors?

**Comment by StuporHero** [comment]
@yegor256 Yes. I just double checked that it is a collaborator with Write privileges. I don’t mind granting you access to the repository to troubleshoot it since I was planning to submit it as an RfP for Zerocracy anyway after I got it setup.

**Comment by yegor256** [comment]
@StuporHero yes, please, give me access to the repo, I will see what's going on...

**Comment by StuporHero** [comment]
I’ve added you as a collaborator. Do whatever you need to do. I’m not worried about the code that’s currently in there.

**Comment by yegor256** [comment]
@StuporHero the problem is that the repo is too big (too many files, 5114) and it takes too long to parse them. You can try locally from command line:

```
pdd -v -f /dev/null
```

I will try to fix the problem now and make 0pdd more tolerant to such situations.

**Comment by StuporHero** [comment]
@yegor256 Thank you! I appreciate the help.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#204` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @stuporhero[/z](https://www.0crat.com/u/stuporhero)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@StuporHero this is what I see in logs:

```
2018-05-21T05:39:21.387028+00:00 app[web.1]: /app/objects/exec.rb:49:in `value': execution expired (Timeout::Error)
2018-05-21T05:39:21.387052+00:00 app[web.1]: from /app/objects/exec.rb:49:in `block in run'
2018-05-21T05:39:21.387054+00:00 app[web.1]: from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
2018-05-21T05:39:21.387055+00:00 app[web.1]: from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
2018-05-21T05:39:21.387057+00:00 app[web.1]: from /app/objects/exec.rb:48:in `run'
2018-05-21T05:39:21.387059+00:00 app[web.1]: from /app/objects/git_repo.rb:64:in `xml'
2018-05-21T05:39:21.387060+00:00 app[web.1]: from /app/objects/puzzles.rb:36:in `deploy'
2018-05-21T05:39:21.387062+00:00 app[web.1]: from /app/objects/job.rb:38:in `proceed'
2018-05-21T05:39:21.387064+00:00 app[web.1]: from /app/objects/job_starred.rb:33:in `proceed'
2018-05-21T05:39:21.387065+00:00 app[web.1]: from /app/objects/job_recorded.rb:32:in `proceed'
2018-05-21T05:39:21.387071+00:00 app[web.1]: from /app/objects/job_emailed.rb:35:in `proceed'
2018-05-21T05:39:21.387073+00:00 app[web.1]: from /app/objects/job_commiterrors.rb:36:in `proceed'
2018-05-21T05:39:21.387119+00:00 app[web.1]: from /app/objects/job_detached.rb:49:in `block in exclusive'
2018-05-21T05:39:21.387122+00:00 app[web.1]: from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
2018-05-21T05:39:21.387123+00:00 app[web.1]: from /app/objects/job_detached.rb:47:in `exclusive'
2018-05-21T05:39:21.387125+00:00 app[web.1]: from /app/objects/job_detached.rb:37:in `block in proceed'
2018-05-21T05:39:21.387126+00:00 app[web.1]: from /app/objects/job_detached.rb:37:in `fork'
2018-05-21T05:39:21.387128+00:00 app[web.1]: from /app/objects/job_detached.rb:37:in `proceed'
2018-05-21T05:39:21.387130+00:00 app[web.1]: from /app/0pdd.rb:346:in `block in <top (required)>'
2018-05-21T05:39:21.387132+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
2018-05-21T05:39:21.387134+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
2018-05-21T05:39:21.387135+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
2018-05-21T05:39:21.387137+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
2018-05-21T05:39:21.387138+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
2018-05-21T05:39:21.387140+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
2018-05-21T05:39:21.387142+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
2018-05-21T05:39:21.387143+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
2018-05-21T05:39:21.387149+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
2018-05-21T05:39:21.387151+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
2018-05-21T05:39:21.387152+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
2018-05-21T05:39:21.387154+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
2018-05-21T05:39:21.387156+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
2018-05-21T05:39:21.387157+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
2018-05-21T05:39:21.387159+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
2018-05-21T05:39:21.387160+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
2018-05-21T05:39:21.387162+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
2018-05-21T05:39:21.387164+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
2018-05-21T05:39:21.387165+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
2018-05-21T05:39:21.387169+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
2018-05-21T05:39:21.387167+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
2018-05-21T05:39:21.387170+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
2018-05-21T05:39:21.387171+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
2018-05-21T05:39:21.387173+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
2018-05-21T05:39:21.387175+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
2018-05-21T05:39:21.387176+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
2018-05-21T05:39:21.387177+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
2018-05-21T05:39:21.387179+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
2018-05-21T05:39:21.387180+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
2018-05-21T05:39:21.387182+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
2018-05-21T05:39:21.387183+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
2018-05-21T05:39:21.387184+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
2018-05-21T05:39:21.387186+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
2018-05-21T05:39:21.387187+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
2018-05-21T05:39:21.387189+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
2018-05-21T05:39:21.387190+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
2018-05-21T05:39:21.387195+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
2018-05-21T05:39:21.387197+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
2018-05-21T05:39:21.387200+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
2018-05-21T05:39:21.387201+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
2018-05-21T05:39:21.387203+00:00 app[web.1]: from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
2018-05-21T05:39:21.387204+00:00 app[web.1]: from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
2018-05-21T05:39:21.387205+00:00 app[web.1]: from /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

`Timeout::Error` occurs but for some reason we don't report it to GitHub... investigating.

**Comment by yegor256** [comment]
@StuporHero the reporting problem is fixed in 6813afd563ac6a0607fb5bc36d0ed1dd4c07babd. Now we see the problem in comments: https://github.com/sunsofterp/phoenix/commit/0bdd9ab27ccc836ee4d4f7a855185ca9afc785aa Let me try to fix the timeout issue.

**Comment by yegor256** [comment]
@StuporHero wait a sec, I suspect it's not the timeout issue now, since we have a similar problem in another repository, where the amount of files is way smaller: https://github.com/yegor256/0pdd/issues/205 I'm investigating. Thanks for offering help and contribution! You can actually donate some money to this repository/project, it will definitely help us to improve it: https://www.0crat.com/contrib/C3T46CUJJ

**Comment by yegor256** [comment]
@StuporHero I don't know what I did, but the problem is fixed, thanks to 5af5f085c28fa8f9240021dfb3af77d50b737990 :)

**Comment by StuporHero** [comment]
@yegor256 Works for me! Thanks again for your help!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#204](https://github.com/yegor256/0pdd/issues/204) is now out of scope
