### ISSUE TITLE
TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#206]
https://sentry.io/zerocracy/0pdd-j0/issues/553746512/

```
TypeError: no implicit conversion of String into Integer
  objects/commit_tickets.rb:39:in `dig'
    unless @sources.config.dig('alerts', 'suppress', 'on-found-puzzle')
  objects/commit_tickets.rb:39:in `submit'
    unless @sources.config.dig('alerts', 'suppress', 'on-found-puzzle')
  objects/emailed_tickets.rb:35:in `submit'
    done = @tickets.submit(puzzle)
  objects/sentry_tickets.rb:46:in `submit'
    @tickets.submit(puzzle)
  objects/puzzles.rb:91:in `block in expose'
    issue = tickets.submit(puzzle)
...
(62 additional frame(s) were not displayed)

TypeError: no implicit conversion of String into Integer
```

**Comment by 0crat** [comment]
Job [#206](https://github.com/yegor256/0pdd/issues/206) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@yegor256 I need permission to zerocracy organization in sentry.io to see full issue list

**Comment by yegor256** [comment]
@pbenety send me your email in Telegram and I will invite you to Sentry

**Comment by pbenety** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/0pdd/issues/206#issuecomment-399768847))

@pbenety The impediment for [#206](https://github.com/yegor256/0pdd/issues/206) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by proshin-roman** [comment]
@yegor256 @pbenety any news here? I've got the same problem in my repo: https://github.com/proshin-roman/blog/pull/172

**Comment by pbenety** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/0pdd/issues/206#issuecomment-425874417))

@pbenety The user @pbenety[/z](https://www.0crat.com/u/pbenety) resigned from [#206](https://github.com/yegor256/0pdd/issues/206), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by amihaiemil** [comment]
@yegor256 same problem in amihaiemil/docker-java-api :(

**Comment by php-coder** [comment]
@yegor256 Any plans on fixing this issue?

**Comment by yegor256** [comment]
@lastk can you please take a look?

**Comment by lastk** [comment]
@yegor256 yes. I need more details on it though
