### ISSUE TITLE
Octokit::NotFound: GET https://api.github.com/repos/nopparat-mkw/profile/issues/2: 404 - Not Found // See: https://d...

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#207]
https://sentry.io/zerocracy/0pdd-j0/issues/512290290/

```
Octokit::NotFound: GET https://api.github.com/repos/nopparat-mkw/profile/issues/2: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue
  octokit/response/raise_error.rb:16:in `on_complete'
    raise error
  faraday/response.rb:9:in `block in call'
    on_complete(environment)
  faraday/response.rb:61:in `on_complete'
    yield(env)
  faraday/response.rb:8:in `call'
    @app.call(env).on_complete do |environment|
  octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    response = @app.call(env)
...
(76 additional frame(s) were not displayed)

Octokit::NotFound: GET https://api.github.com/repos/nopparat-mkw/profile/issues/2: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue
```

**Comment by 0crat** [comment]
Job [#207](https://github.com/yegor256/0pdd/issues/207) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#207](https://github.com/yegor256/0pdd/issues/207) assigned to @liligga[/z](https://www.0crat.com/u/liligga), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1750817723); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/0pdd/issues/207#issuecomment-399746227))

@yegor256 The user @liligga[/z](https://www.0crat.com/u/liligga) resigned from [#207](https://github.com/yegor256/0pdd/issues/207), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#207](https://github.com/yegor256/0pdd/issues/207) assigned to @fybwid[/z](https://www.0crat.com/u/fybwid), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1800632458); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by fybwid** [comment]
@0crat wait
@yegor256 I need more details with this issues and I'am unable to view https://sentry.io/zerocracy/0pdd-j0/issues/512290290/

**Comment by 0crat** [comment]
> @0crat wait @yegor256 I need more details with this issues and I'am unable to view https://sentr... ([here](https://github.com/yegor256/0pdd/issues/207#issuecomment-401262350))

@fybwid The impediment for [#207](https://github.com/yegor256/0pdd/issues/207) was registered successfully by @fybwid[/z](https://www.0crat.com/u/fybwid)
