### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#212]
0pdd returns an error for a webhook:
```
403 - API rate limit exceeded for user ID 24456188. // See: https://developer.github.com/v3/#rate-limiting
	/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.1/lib/faraday/response.rb:9:in `block in call&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.1/lib/faraday/response.rb:61:in `on_complete&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.1/lib/faraday/response.rb:8:in `call&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.1/lib/faraday/rack_builder.rb:143:in `build_response&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.1/lib/faraday/connection.rb:387:in `run_request&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.1/lib/faraday/connection.rb:138:in `get&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:19:in `get&#39;
	/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/client/repositories.rb:29:in `repository&#39;
	/app/0pdd.rb:400:in `repo&#39;
	/app/0pdd.rb:295:in `block in &lt;top (required)&gt;&#39;
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#212](https://github.com/yegor256/0pdd/issues/212) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#212](https://github.com/yegor256/0pdd/issues/212) assigned to @robsonataide[/z](https://www.0crat.com/u/robsonataide), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1750814617); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The job [#212](https://github.com/yegor256/0pdd/issues/212) assigned to @fybwid[/z](https://www.0crat.com/u/fybwid), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1800627401); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by fybwid** [comment]
@0crat wait
@yegor256 I need more details with this issue

**Comment by 0crat** [comment]
> @0crat wait @yegor256 I need more details with this issue ([here](https://github.com/yegor256/0pdd/issues/212#issuecomment-401262955))

@fybwid The impediment for [#212](https://github.com/yegor256/0pdd/issues/212) was registered successfully by @fybwid[/z](https://www.0crat.com/u/fybwid)

**Comment by fybwid** [comment]
The current API limit rate is 5000 request per hour [noted here](https://developer.github.com/v3/#rate-limiting). @yegor256, is[Conditional Requests](https://developer.github.com/v3/#conditional-requests) possible to do?

**Comment by fybwid** [comment]
@g4s8 The current API limit rate is 5000 request per hour [noted here](https://developer.github.com/v3/#rate-limiting) and your log also display it at first line.

My opinion, is not the 0pdd who can't get the webhook but it's because the current user is over the allowed quota.

**Comment by g4s8** [comment]
@fybwid but this log was posted as a comment by 0pdd user, so current user is 0pdd in this log. And I don't think it's a webhook quota, but API quota - 0pdd uses Github API to post comments and close tickets.

**Comment by fybwid** [comment]
@g4s8 yes, I'm agree that it wasn't the webhook quota but API quota. It's the same as what I said before, and for more details, on your first line log `403 - API rate limit exceeded for user ID 24456188. // See: https://developer.github.com/v3/#rate-limiting`, is this `user ID 24456188` belong to 0pdd?
Also in my opinion, the webhook process is happened but because it's exceed the API limit rate then we got  `403`.

**Comment by g4s8** [comment]
@fybwid yes, it's 0pdd user, see https://api.github.com/user/24456188

**Comment by fybwid** [comment]
I've find sample here:
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/conditional_get.rb

and here:
https://www.rubydoc.info/gems/sinatra/Sinatra%2FHelpers:etag

Still, I need more enlightenment with applying the conditional requests.
