### ISSUE TITLE
Octokit::BadGateway: GET https://api.github.com/repos/Harvest-foundation/telegram-bot/issues/39: 502 - Server Error

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#214]
https://sentry.io/zerocracy/0pdd-j0/issues/564139299/

```
Octokit::BadGateway: GET https://api.github.com/repos/Harvest-foundation/telegram-bot/issues/39: 502 - Server Error
  octokit/response/raise_error.rb:16:in `on_complete'
    raise error
  faraday/response.rb:9:in `block in call'
    on_complete(environment)
  faraday/response.rb:61:in `on_complete'
    yield(env)
  faraday/response.rb:8:in `call'
    @app.call(env).on_complete do |environment|
  octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    response = @app.call(env)
...
(71 additional frame(s) were not displayed)

Octokit::BadGateway: GET https://api.github.com/repos/Harvest-foundation/telegram-bot/issues/39: 502 - Server Error
```

Full stacktrace:

```
Octokit::BadGateway: GET https://api.github.com/repos/Harvest-foundation/telegram-bot/issues/39: 502 - Server Error
  from octokit/response/raise_error.rb:16:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:61:in `on_complete'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:138:in `get'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:19:in `get'
  from octokit/client/issues.rb:114:in `issue'
  from objects/github_tickets.rb:61:in `close'
  from objects/logged_tickets.rb:61:in `close'
  from objects/github_tagged_tickets.rb:77:in `close'
  from objects/commit_tickets.rb:54:in `close'
  from objects/emailed_tickets.rb:63:in `close'
  from objects/sentry_tickets.rb:56:in `close'
  from objects/puzzles.rb:76:in `block in expose'
  from objects/puzzles.rb:68:in `loop'
  from objects/puzzles.rb:68:in `expose'
  from objects/puzzles.rb:33:in `deploy'
  from objects/job.rb:38:in `proceed'
  from objects/job_starred.rb:33:in `proceed'
  from objects/job_recorded.rb:32:in `proceed'
  from objects/job_emailed.rb:35:in `proceed'
  from objects/job_commiterrors.rb:36:in `proceed'
  from objects/job_detached.rb:48:in `exclusive'
  from objects/job_detached.rb:36:in `block in proceed'
  from objects/job_detached.rb:36:in `fork'
  from objects/job_detached.rb:36:in `proceed'
  from 0pdd.rb:342:in `block in <top (required)>'
  from sinatra/base.rb:1634:in `call'
  from sinatra/base.rb:1634:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1039:in `block in process_route'
  from sinatra/base.rb:1037:in `catch'
  from sinatra/base.rb:1037:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1096:in `block in dispatch!'
  from sinatra/base.rb:1075:in `block in invoke'
  from sinatra/base.rb:1075:in `catch'
  from sinatra/base.rb:1075:in `invoke'
  from sinatra/base.rb:1093:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1075:in `block in invoke'
  from sinatra/base.rb:1075:in `catch'
  from sinatra/base.rb:1075:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1501:in `block in call'
  from sinatra/base.rb:1728:in `synchronize'
  from sinatra/base.rb:1501:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

Let's catch these situations (`Octokit::ServerError`) and email the repo admin. If it's defined in the configuration. If not, just email to `github-server-error@0pdd.com`

**Comment by 0crat** [comment]
Job [#214](https://github.com/yegor256/0pdd/issues/214) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
dup of #212

**Comment by 0crat** [comment]
The job [#214](https://github.com/yegor256/0pdd/issues/214) is now out of scope
