### ISSUE TITLE
Octokit::TooManyRequests: GET https://api.github.com/repos/yegor256/zold: 403 - API rate limit exceeded for user ID 2445618...

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#215]
https://sentry.io/zerocracy/0pdd-j0/issues/562451763/

```
Octokit::TooManyRequests: GET https://api.github.com/repos/yegor256/zold: 403 - API rate limit exceeded for user ID 24456188. // See: https://developer.github.com/v3/#rate-limiting
  octokit/response/raise_error.rb:16:in `on_complete'
    raise error
  faraday/response.rb:9:in `block in call'
    on_complete(environment)
  faraday/response.rb:61:in `on_complete'
    yield(env)
  faraday/response.rb:8:in `call'
    @app.call(env).on_complete do |environment|
  octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    response = @app.call(env)
...
(53 additional frame(s) were not displayed)

Octokit::TooManyRequests: GET https://api.github.com/repos/yegor256/zold: 403 - API rate limit exceeded for user ID 24456188. // See: https://developer.github.com/v3/#rate-limiting
```

Full st:

```
Octokit::TooManyRequests: GET https://api.github.com/repos/yegor256/zold: 403 - API rate limit exceeded for user ID 24456188. // See: https://developer.github.com/v3/#rate-limiting
  from octokit/response/raise_error.rb:16:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:61:in `on_complete'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:138:in `get'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:19:in `get'
  from octokit/client/repositories.rb:29:in `repository'
  from 0pdd.rb:397:in `repo'
  from 0pdd.rb:292:in `block in <top (required)>'
  from sinatra/base.rb:1634:in `call'
  from sinatra/base.rb:1634:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1039:in `block in process_route'
  from sinatra/base.rb:1037:in `catch'
  from sinatra/base.rb:1037:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1096:in `block in dispatch!'
  from sinatra/base.rb:1075:in `block in invoke'
  from sinatra/base.rb:1075:in `catch'
  from sinatra/base.rb:1075:in `invoke'
  from sinatra/base.rb:1093:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1075:in `block in invoke'
  from sinatra/base.rb:1075:in `catch'
  from sinatra/base.rb:1075:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1501:in `block in call'
  from sinatra/base.rb:1728:in `synchronize'
  from sinatra/base.rb:1501:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

Let's fix this by checking the quota first. If it's over, don't check invitations.

**Comment by 0crat** [comment]
Job [#215](https://github.com/yegor256/0pdd/issues/215) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
dup of #213

**Comment by 0crat** [comment]
The job [#215](https://github.com/yegor256/0pdd/issues/215) is now out of scope
