### ISSUE TITLE
Test Basic Fails

### ISSUE THREAD

**Issue by timeracers** [yegor256/0pdd#227]
When I run all the tests the test "test_basic" fails.
Here is the log I get when i try to run it:
```
ERROR: Puzzle 9el/a.txt:1-1 has an estimate of 0 minutes, which is lower than 30 minutesThe system cannot find the path specified.


Minitest::UnexpectedError: RuntimeError: doesn't match '/puzzles/puzzle[file="a.txt"]': <?xml version="1.0"?>
<?xml-stylesheet type='text/xsl' href='http://pdd-xsl.teamed.io/1.0.snapshot.xsl'?>
<puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://pdd-xsd.teamed.io/1.0.snapshot.xsd" version="1.0.snapshot" date="2018-07-11T23:37:20Z">
  <puzzle>
    <ticket>55</ticket>
    <estimate>0</estimate>
    <role>DEV</role>
    <id>55-5a8dd3ad</id>
    <lines>1-1</lines>
    <body>hello!</body>
    <file>3cm/a.txt</file>
  </puzzle>
</puzzles>

    C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:106:in `block in matches'
    C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:105:in `each'
    C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:105:in `matches'
    C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:36:in `block in test_basic'
    C:/Ruby23-x64/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
    C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:33:in `test_basic'
C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:106:in `block in matches'
C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:105:in `each'
C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:105:in `matches'
C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:36:in `block in test_basic'
C:/Ruby23-x64/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
C:/Users/Tim Reinagel/Documents/pdd/test/test_pdd.rb:33:in `test_basic'
```

I'm using windows.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by timeracers** [comment]
Whoops, wrong project that was pdd.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#227` is not assigned, can't get performer
