### ISSUE TITLE
How to Contribute guide doesn't work

### ISSUE THREAD

**Issue by timeracers** [yegor256/0pdd#228]
After following the guide and trying to run the tests.
The test framework quits unexpectedly.
This is the log I get:
```
Testing started at 9:43 PM ...
C:\Ruby23-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby23-x64\bin/rake test
Test config is absent
Cannot do operations on a non-existent table
DynamoDB Local table: ACTIVE
DynamoDB Local is running in PID 5016
C:/Users/Tim Reinagel/Documents/0pdd/.simplecov:22:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
Coverage report generated for Unit Tests to C:/Users/Tim Reinagel/Documents/0pdd/coverage. 261 / 800 LOC (32.63%) covered.
C:/Users/Tim Reinagel/Documents/0pdd/objects/exec.rb:60:in `block (2 levels) in run': set -x && set -e && set -o pipefail && ruby -e "print RUBY_VERSION" [127]: (Exec::Error)
+ set -e
+ set -o pipefail
+ ruby -e 'print RUBY_VERSION'
/bin/bash: ruby: command not found

	from C:/Ruby23-x64/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
	from C:/Ruby23-x64/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from C:/Users/Tim Reinagel/Documents/0pdd/objects/exec.rb:54:in `block in run'
	from C:/Ruby23-x64/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from C:/Ruby23-x64/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from C:/Ruby23-x64/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from C:/Ruby23-x64/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from C:/Ruby23-x64/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from C:/Users/Tim Reinagel/Documents/0pdd/objects/exec.rb:53:in `run'
	from C:/Users/Tim Reinagel/Documents/0pdd/0pdd.rb:111:in `block in <top (required)>'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1425:in `configure'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1925:in `block (2 levels) in delegate'
	from C:/Users/Tim Reinagel/Documents/0pdd/0pdd.rb:60:in `<top (required)>'
	from C:/Users/Tim Reinagel/Documents/0pdd/test/test_0pdd.rb:25:in `require_relative'
	from C:/Users/Tim Reinagel/Documents/0pdd/test/test_0pdd.rb:25:in `<top (required)>'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `require'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `select'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1)
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
C:/Users/Tim Reinagel/Documents/0pdd/Rakefile:61:in ``': No such file or directory - kill -TERM 5016 (Errno::ENOENT)
	from C:/Users/Tim Reinagel/Documents/0pdd/Rakefile:61:in `block (2 levels) in <top (required)>'

Process finished with exit code 1
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@timeracers we never tried it on Windows...

**Comment by 0crat** [comment]
Job [#228](https://github.com/yegor256/0pdd/issues/228) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @timeracers[/z](https://www.0crat.com/u/timeracers)

**Comment by pdacostaporto** [comment]
Sorry for the noise, but development environment could be easily automated with [Vagrant](https://www.vagrantup.com/) so newcomers can hit the ground running regardless of their OS instead of having to configure the right versions for everything (took considerable time for me on an Ubuntu machine).

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/0pdd/issues/228#issuecomment-416211183))

@g4s8 This is what I know about this job in [C3T46CUJJ](https://www.0crat.com/p/C3T46CUJJ), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#228](https://github.com/yegor256/0pdd/issues/228) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @timeracers[/z](https://www.0crat.com/u/timeracers): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T46CUJJ?q=%7Bjob%3A%27gh%3Ayegor256%2F0pdd%23228%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#228](https://github.com/yegor256/0pdd/issues/228) assigned to @dferdian[/z](https://www.0crat.com/u/dferdian), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/2610526324); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@dferdian[/z](https://www.0crat.com/u/dferdian) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by lastk** [comment]
@yegor256 there are a lot of shell commands in the app which works only on linux. should we close this issue?

**Comment by yegor256** [comment]
@lastk yes, I think we can officially say in the README file that only Linux/Mac is supported. Windows is something we don't support and won't support.
