### ISSUE TITLE
Octokit::NotFound: GET https://api.github.com/repos/fidals/shopelectro/issues/rf182: 404 - Not Found // See: https:/...

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#248]
https://sentry.io/zerocracy/0pdd-j0/issues/729723315/

```
Octokit::NotFound: GET https://api.github.com/repos/fidals/shopelectro/issues/rf182: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue
  octokit/response/raise_error.rb:16:in `on_complete'
    raise error
  faraday/response.rb:9:in `block in call'
    on_complete(environment)
  faraday/response.rb:61:in `on_complete'
    yield(env)
  faraday/response.rb:8:in `call'
    @app.call(env).on_complete do |environment|
  octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    response = @app.call(env)
...
(72 additional frame(s) were not displayed)

Octokit::NotFound: GET https://api.github.com/repos/fidals/shopelectro/issues/rf182: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue
```

```
Octokit::NotFound: GET https://api.github.com/repos/fidals/shopelectro/issues/rf182: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue
  from octokit/response/raise_error.rb:16:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:61:in `on_complete'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/request/retry.rb:128:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:138:in `get'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:19:in `get'
  from octokit/client/issues.rb:114:in `issue'
  from objects/github_tickets.rb:40:in `notify'
  from objects/milestone_tickets.rb:35:in `notify'
  from objects/logged_tickets.rb:36:in `notify'
  from objects/github_tagged_tickets.rb:36:in `notify'
  from objects/commit_tickets.rb:34:in `notify'
  from objects/emailed_tickets.rb:31:in `notify'
  from objects/sentry_tickets.rb:36:in `notify'
  from objects/diff.rb:38:in `block in notify'
  from objects/diff.rb:33:in `each'
  from objects/diff.rb:33:in `notify'
  from objects/job.rb:40:in `proceed'
  from objects/job_starred.rb:33:in `proceed'
  from objects/job_recorded.rb:32:in `proceed'
  from objects/job_emailed.rb:35:in `proceed'
  from objects/job_commiterrors.rb:36:in `proceed'
  from objects/job_detached.rb:48:in `exclusive'
  from objects/job_detached.rb:36:in `block in proceed'
  from objects/job_detached.rb:36:in `fork'
  from objects/job_detached.rb:36:in `proceed'
  from 0pdd.rb:347:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:307:in `block in start_thread'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.8`
