### ISSUE TITLE
failed to login

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#265]
```
NoMethodError: undefined method `[]' for nil:NilClass
  from 0pdd.rb:305:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.17`

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#265` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
