### ISSUE TITLE
XML has 2 errors

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#269]
```
RuntimeError: XML has 2 errors
w6220:0: ERROR: Element 'email': [facet 'pattern'] The value '1W#456eq' is not accepted by the pattern '([0-9a-zA-Z]([-_.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})'.
6220:0: ERROR: Element 'email': '1W#456eq' is not a valid value of the local atomic type.
<?xml version="1.0"?>
<?xml-stylesheet href="/puzzles.xsl" type="text/xsl"?>
<puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.0pdd.com/puzzles.xsd" version="0.9" date="2017-02-08T07:00:44Z">
  <puzzle alive="false">
    <issue href="https://github.com/teamed/xockets-hadoop-transport/issues/7">7</issue>
    <id>5-1efa7ba6</id>
    <ticket>5</ticket>
    <file>src/main/java/com/xockets/hadoop/XsInput.java</file>
    <lines>54-55</lines>
    <estimate>30</estimate>
    <author>unknown</author>
    <email>unknown@0pdd.com</email>
    <time>2016-12-14T08:49:22Z</time>
    <body>There is no unit test for XsInput class. Let's create one to make sure it works as expected</body>
    <role>IMP</role>
    <children>
      <puzzle alive="false">
        <issue>unknown</issue>
        <id>7-fa7dd48e</id>
        <ticket>7</ticket>
        <file>src/test/java/com/xockets/hadoop/ReservePort.java</file>
        <lines>33-34</lines>
        <estimate>30</estimate>
        <author>unknown</author>
        <email>unknown@0pdd.com</email>
        <time>2016-12-14T08:49:22Z</time>
        <body>Refactor this class to allow multiple port reservations in single test case and use it in XsOutputTest.</body>
        <role>IMP</role>
        <children/>
      </puzzle>
    </children>
  </puzzle>
  <puzzle alive="false">
    <issue href="https://github.com/teamed/xockets-hadoop-transport/issues/9">9</issue>
    <id>5-8a982a78</id>
    <ticket>5</ticket>
    <file>src/main/java/com/xockets/hadoop/XsInput.java</file>
    <lines>116-119</lines>
    <estimate>30</estimate>
    <author>unknown</author>
    <email>unknown@0pdd.com</email>
    <time>2016-12-14T08:49:22Z</time>
    <body>Two-seconds sleeping here is a workaround. Instead, we should wait for a signal from Hadoop, which will inform us when all mappers are finished. We should wait till that very moment. Only when all mappers are done, we can start iterating over pairs here.</body>
    <role>DEV</role>
    <children>
      <puzzle alive="false">
        <issue href="https://github.com/teamed/xockets-hadoop-transport/issues/197">197</issue>
        <id>9-b2a2ceff</id>
        <ticket>9</ticket>
        <file>src/main/java/com/xockets/hadoop/XsInput.java</file>
        <lines>92-101</lines>
        <estimate>30</estimate>
        <author>unknown</author>
        <email>unknown@0pdd.com</email>
        <time>2016-12-14T08:49:22Z</time>
        <body>Right now, XsInput is only using a mock implementation of MapSignal. We need to introduce a class that actually communicates Mapper completion information. Most likely, this is going to be implemented using Apache ZooKeeper. Let's call it something like ZkMapSignal. It should allow XsInput to determine how many mapper tasks have already completed so that XsInput may be aware when the data it needs is ready for fetching. Also, let's make XsInput configurable in such a way that it can use both an actual MapSignal instance or the Fake one in case it's needed, say, for unit testing. For more info, see https://github.com/teamed/xockets-hadoop-transport/issues/27</body>
        <role>IMP</role>
        <children>
          <puzzle alive="false">
            <issue>unknown</issue>
            <id>197-f5c28565</id>
            <ticket>197</ticket>
            <file>src/main/java/com/xockets/hadoop/MapSignal.java</file>
            <lines>47-48</lines>
            <estimate>30</estimate>
            <author>unknown</author>
            <email>unknown@0pdd.com</email>
            <time>2016-12-14T08:49:22Z</time>
            <body>Refactor waitUntilFinished to accept job ID for which it waits to finish all mappers.</body>
            <role>IMP</role>
            <children/>
          </puzzle>
          <puzzle alive="false">
            <issue href="https://github.com/teamed/xockets-hadoop-transport/issues/342">342</issue>
            <id>197-9281864b</id>
            <ticket>197</ticket>
            <file>src/main/java/com/xockets/hadoop/ZkMapSignal.java</file>
            <lines>34-36</lines>
            <estimate>30</estimate>
            <author>unknown</author>
            <email>unknown@0pdd.com</email>
            <time>2016-12-14T08:49:22Z</time>
            <body>Implement waitUntilFinished using information provided from finish() method of ZkMessages and us ZkMapSignal instead of MapSignal.Fake in XsInput.</body>
            <role>IMP</role>
            <children>
              <puzzle alive="false">
                <issue>unknown</issue>
                <id>342-0fb8586a</id>
                <ticket>342</ticket>
                <file>src/main/java/com/xockets/hadoop/XsInput.java</file>
                <lines>69-70</lines>
                <estimate>30</estimate>
                <author>unknown</author>
                <email>unknown@0pdd.com</email>
                <time>2016-12-14T08:49:22Z</time>
                <body>Make XsInput use ZkMapSignal instead of MapSignal.Fake when XsOutput begin to notify Messages that all pair finished map task.</body>
                <role>IMP</role>
                <children/>
              </puzzle>
            </children>
          </puzzle>
          <puzzle alive="false">
            <issue href="https://github.com/teamed/xockets-hadoop-transport/issues/341">341</issue>
            <id>197-90ea02f4</id>
            <ticket>197</ticket>
            <file>src/main/java/com/xockets/messaging/ZkMessages.java</file>
            <lines>53-55</lines>
            <estimate>30</estimate>
            <author>unknown</author>
            <email>unknown@0pdd.com</email>
            <time>2016-12-14T08:49:22Z</time>
            <body>Implement finish() method for storing mapper finish status, and call this method when all mappers with given JobID have finished from XsOutput and remove coverageFix() test.</body>
            <role>IMP</role>
            <children>
              <puzzle alive="false">
                <issue>unknown</issue>
                <id>341-78590e59</id>
                <ticket>341</ticket>
                <file>src/main/java/com/xockets/hadoop/XsOutput.java</file>
                <lines>63-64</lines>
                <estimate>30</estimate>
                <author>unknown</author>
                <email>unknown@0pdd.com</email>
                <time>2016-12-14T08:49:22Z</time>
                <body>Call Messages.finish() when all mappers with given JobID have finished from XsOutput and remove coverageFix() test.</body>
                <role>IMP</role>
                <children/>
              </puzzle>
            </children>
          </puzzle>
        </children>
      </puzzle>
    </children>
  </puzzle>
  <puzzle alive="false">
    <issue>unknown</issue>
    <id>5-9402ba70</id>
    <ticket>5</ticket>
    <file>src/main/java/com/xockets/hadoop/XsIterator.java</file>
    <lines>40-41</lines>
    <estimate>30</estimate>
    <author>unknown</author>
    <email>unknown@0pdd.com</email>
    <time>2016-12-14T08:49:22Z</time>
    <body>There is not unit test for this class. Even though it's a simple one, we should create a test, to make sure it works as expected</body>
    <role>IMP</role>
    <children/>
  </puzzle>
  <puzzle alive="false">
    <issue href="https://github.com/teamed/xockets-hadoop-transport/issues/8">8</issue>
    <id>5-7fe0b9fd</id>
    <ticket>5</ticket>
    <file>src/main/java/com/xockets/hadoop/XsOutput.java</file>
    <lines>43-47</lines>
    <estimate>60</estimate>
    <author>unknown</author>
    <email>unknown@0pdd.com</email>
    <time>2016-12-14T08:49:22Z</time>
    <body>Output collector implementation is over-simplified. Even though it works in this form, I believe we're missing some important features that have to be implemented in this class. Let's investigate what exactly is happening in MapTask.MapOutputBuffer (default Hadoop implementation o...
  from objects/safe_storage.rb:44:in `valid'
  from objects/safe_storage.rb:37:in `save'
  from objects/upgraded_storage.rb:47:in `save'
  from objects/upgraded_storage.rb:41:in `load'
  from objects/sync_storage.rb:31:in `block in load'
  from objects/sync_storage.rb:31:in `synchronize'
  from objects/sync_storage.rb:31:in `load'
  from 0pdd.rb:240:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:307:in `block in start_thread'
```

**Comment by yegor256** [comment]
@lastk can you please take a look?

**Comment by 0crat** [comment]
Job [#269](https://github.com/yegor256/0pdd/issues/269) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
