### ISSUE TITLE
default labels

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#27]
Let's make it possible to configure default labels for all GitHub issues created by @0pdd. Somewhere in `.0pdd.yml` let's create a config section for it:

```yaml
tags:
  - bug
  - urgent
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.27`

**Comment by php-coder** [comment]
For the record: the implementation differs from the proposed in the issues body. Here is an example of using the new feature (not also that it should be in `.0pdd.yml` file): https://github.com/yegor256/0pdd/commit/60aa0eaf35d6afe7704471a9dc22604953dc7c13

**Comment by yegor256** [comment]
@php-coder I updated the description of the ticket, thanks

**Comment by php-coder** [comment]
@yegor256 Another one: s/Somewhere in .pdd/Somewhere in .0pdd/

**Comment by php-coder** [comment]
@yegor256 There are a few errors in the build log that didn't fails the build bug look suspicious to me:

1) This could be a real error:
```
+ ruby test/test_credentials.rb
Coverage report generated for Unit Tests to /home/r/repo/coverage. 60 / 160 LOC (37.5%) covered.
Loaded suite test/test_credentials
Started
32;1m.0mS3 17661 from xml.0pdd.com/yegor256/0pdd.xml
32;1m.0m32;1m.0m33mE0m
===============================================================================
Error: 40;33;1mtest_connects_to_github(CredentialsTest)0m: NoMethodError: undefined method `safe' for #<GithubTickets:0x000000009cd970>
test/test_credentials.rb:65:in `test_connects_to_github'
	 62:     tickets = GithubTickets.new(
	 63:       nil, github, 'yegor256/0pdd'
	 64:     )
40;33;1m  => 65:     assert(!tickets.safe.nil?)0m
	 66:   end
	 67:
	 68:   def test_connects_to_aws_s3
===============================================================================
32;1m.0m

Finished in 6.470823486 seconds.
33m------0m
5 tests, 3 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
```

2) The next one probably is expected to happen, but is it possible to not show the exception in this case?
```
[INFO] --- jcabi-dynamodb-maven-plugin:0.9:create-tables (dynamodb-integration-test) @ dynamodb-local ---
[INFO] >> Initializing DynamoDB Local with the following configuration:
[INFO] >> Port: 38175
[INFO] >> InMemory:     true
[INFO] >> DbPath:       null
[INFO] >> SharedDb:     false
[INFO] >> shouldDelayTransientStatuses: false
[INFO] >> CorsParams:   *
[INFO] >>
Dec 04, 2017 11:14:01 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
		at java.net.PlainSocketImpl.socketConnect(Native Method)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		at java.net.Socket.connect(Socket.java:580)
		at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
		at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
		at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
		at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
		at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
		at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
		at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822)
		at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
		at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
		at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
		at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1820)
		at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1099)
		at com.amazonaws.services.dynamodbv2.util.TableUtils.waitForTableDescription(TableUtils.java:201)
		at com.amazonaws.services.dynamodbv2.util.TableUtils.waitUntilExists(TableUtils.java:100)
		at com.jcabi.dynamodb.core.Tables.exists(Tables.java:160)
		at com.jcabi.dynamodb.core.Tables.create(Tables.java:134)
		at com.jcabi.dynamodb.maven.plugin.CreateTablesMojo.run(CreateTablesMojo.java:89)
		at com.jcabi.dynamodb.maven.plugin.AbstractDynamoMojo.execute(AbstractDynamoMojo.java:103)
		at com.jcabi.dynamodb.maven.plugin.CreateTablesMojo.execute(CreateTablesMojo.java:48)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Cannot do operations on a non-existent table
[INFO] Waiting for table '0pdd-events' to become active
[INFO] Table '0pdd-events' is now ready for use
[INFO]
[INFO] --- jcabi-dynamodb-maven-plugin:0.9:wait (dynamodb-integration-test) @ dynamodb-local ---
[INFO] DynamoDB Local is listening on port 38175... (Ctrl-C to stop)
DynamoDB Local table: ACTIVE
DynamoDB Local is running in PID 11602
Coverage report generated for Unit Tests to /home/r/repo/coverage. 253 / 687 LOC (36.83%) covered.
Loaded suite /usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_test_loader
Started
```

**Comment by php-coder** [comment]
> 32;1m.0mS3 17661 from xml.0pdd.com/yegor256/0pdd.xml
> 32;1m.0m32;1m.0m33mE0m

The messages also could be improved by disabling colored output from the commands (or properly filtering such an output).

**Comment by yegor256** [comment]
@php-coder I created #156 thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#27`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#27` is not in scope.

**Comment by php-coder** [comment]
It's puzzling me because the issue mentioning "labels" in title, it operates on tags in the code, it uses "tags" in the configuration, but it still tries to add "labels".

Consider renaming it while it's not too late.
