### ISSUE TITLE
Net::ReadTimeout: Net::ReadTimeout

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#270]
Found this in Sentry today:

```
Net::ReadTimeout: Net::ReadTimeout
  from net/protocol.rb:217:in `rbuf_fill'
  from net/protocol.rb:191:in `readuntil'
  from net/protocol.rb:201:in `readline'
  from net/http/response.rb:40:in `read_status_line'
  from net/http/response.rb:29:in `read_new'
  from net/http.rb:1509:in `block in transport_request'
  from net/http.rb:1506:in `catch'
  from net/http.rb:1506:in `transport_request'
  from net/http.rb:1479:in `request'
  from net/http.rb:1472:in `block in request'
  from net/http.rb:920:in `start'
  from net/http.rb:1470:in `request'
  from faraday/adapter/net_http.rb:87:in `perform_request'
  from faraday/adapter/net_http.rb:43:in `block in call'
  from faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  from faraday/adapter/net_http.rb:38:in `call'
  from faraday/response.rb:8:in `call'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/request/retry.rb:128:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:175:in `patch'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:46:in `patch'
  from octokit/client/organizations.rb:693:in `update_organization_membership'
  from objects/github_invitations.rb:41:in `block in accept_orgs'
  from objects/github_invitations.rb:37:in `each'
  from objects/github_invitations.rb:37:in `accept_orgs'
  from 0pdd.rb:250:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:307:in `block in start_thread'
```

**Comment by yegor256** [comment]
@lastk can you please take a look?

**Comment by 0crat** [comment]
Job [#270](https://github.com/yegor256/0pdd/issues/270) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
