### ISSUE TITLE
/issues/unknown: 404 - Not Found

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#44]
```
PATCH https://api.github.com/repos/foo/foo/issues/unknown: 404 - Not Found // See: https://developer.github.com/v3/issues/#edit-an-issue

/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `patch'
/app/vendor/bundle/ruby/2.2.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.6.2/lib/octokit/connection.rb:46:in `patch'
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.6.2/lib/octokit/client/issues.rb:130:in `close_issue'
/app/objects/github_tickets.rb:75:in `close'
/app/objects/puzzles.rb:88:in `block in close'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `each'
/app/objects/puzzles.rb:88:in `close'
/app/objects/puzzles.rb:41:in `deploy'
/app/objects/job.rb:42:in `proceed'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.8.1`
