### ISSUE TITLE
/css/main.css doesn't render

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#477]
```
undefined method `sass&#39; for #&lt;Sinatra::Application:0x00007fee80d001f8&gt;
	/app/0pdd.rb:410:in `block in &lt;top (required)&gt;&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `call&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `block in compile!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (3 levels) in route!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1037:in `route_eval&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (2 levels) in route!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1068:in `block in process_route&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `catch&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `process_route&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1017:in `block in route!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `each&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `route!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1138:in `block in dispatch!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1133:in `dispatch!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `block in call!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `call!&#39;
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:938:in `call&#39;
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.9`
