### ISSUE TITLE
Github hook's handling fails with a 503 error

### ISSUE THREAD

**Issue by nergal-perm** [yegor256/0pdd#572]
After fixing #567 I am able to see my puzzles again, but now 0pdd web service answers with HTTP code 503 to all the POST requests (Github hooks). The response body contains an HTML with the following error:

```
undefined method `rewind' for #<Rackup::Handler::WEBrick::Input:0x00007f119add5b28  // here is a huge wall of text, see attached TXT file

  request.body.rewind
              ^^^^^^^
	/app/0pdd.rb:353:in `block in <top (required)>'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `block in compile!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1089:in `route_eval'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1120:in `block in process_route'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `catch'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `process_route'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1069:in `block in route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `each'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1190:in `block in dispatch!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1185:in `dispatch!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `block in call!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `call!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:990:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/deflater.rb:47:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/xss_header.rb:20:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/path_traversal.rb:18:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/json_csrf.rb:28:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/base.rb:53:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/base.rb:53:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/frame_options.rb:33:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/logger.rb:19:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/common_logger.rb:43:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:266:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:259:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/head.rb:15:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/method_override.rb:28:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:2115:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1674:in `block in call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1890:in `synchronize'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1674:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rackup-2.1.0/lib/rackup/handler/webrick.rb:111:in `service'
	/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

So, right now no added/removed puzzle markers are handled for my project (https://github.com/nergal-perm/java-decita).

Attachments:

- [error.txt](https://github.com/yegor256/0pdd/files/14221717/error.txt) - an HTML with the error stacktrace
- [request.json](https://github.com/yegor256/0pdd/files/14221726/request.json) - the content of the github hook request

**Comment by yegor256** [comment]
@pnatashap maybe you can help?

**Comment by pnatashap** [comment]
rewind is deleted also from rack 3.0, will check for hotfix
https://github.com/rack/rack/discussions/1972

**Comment by h1alexbel** [comment]
the same

**Comment by pnatashap** [comment]
fix is merged but not released
@yegor256 may be new release is needed?

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.11`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.11`

**Comment by yegor256** [comment]
@pnatashap I released a new version manually

**Comment by nergal-perm** [comment]
@yegor256 , @pnatashap , the result is still 503, but the error text changed:

```
no implicit conversion of nil into String
	/app/vendor/bundle/ruby/3.1.0/gems/json-2.7.1/lib/json/common.rb:219:in `initialize&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/json-2.7.1/lib/json/common.rb:219:in `new&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/json-2.7.1/lib/json/common.rb:219:in `parse&#39;
	/app/0pdd.rb:359:in `block in &lt;top (required)&gt;&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `block in compile!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (3 levels) in route!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1089:in `route_eval&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (2 levels) in route!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1120:in `block in process_route&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `catch&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `process_route&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1069:in `block in route!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `each&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `route!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1190:in `block in dispatch!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1185:in `dispatch!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `block in call!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `call!&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:990:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/rewindable_input.rb:25:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/deflater.rb:47:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/xss_header.rb:20:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/path_traversal.rb:18:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/json_csrf.rb:28:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/base.rb:53:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/base.rb:53:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/frame_options.rb:33:in `call&#39;
	/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/logger.rb:19:in `call&#39;
	/app/vendor/b
```

Sorry, it's truncated in the webhook details view.

**Comment by yegor256** [comment]
@nergal-perm new version released, please try again (changes: a627116401e96ade0faa4a3dea5400198b8c8a4b)

**Comment by nergal-perm** [comment]
@yegor256 HTTP code 400, error message is `URL-encoded content is expected in the "payload" query parameter, but it is not provided`

**Comment by nergal-perm** [comment]
I've tried it both ways - manually and redelivering last unsuccessful Github webhook. Both gave that response.

I should try to push some commits to `master` branch and trigger the webhook in "usual" way, though.

**Comment by yegor256** [comment]
@nergal-perm if it fails, please attach a screenshot from Github webhooks page

**Comment by nergal-perm** [comment]
* ![request headers](https://github.com/yegor256/0pdd/assets/4876699/6dbe27f5-9828-4116-8a9b-9eae175c6b89)
* [request payload](https://github.com/yegor256/0pdd/files/14260920/request.json)
* ![response](https://github.com/yegor256/0pdd/assets/4876699/486ac283-7bd4-4705-bb3c-cd6c96bc66e9)


Failed.
Screenshots and the payload attached.

**Comment by yegor256** [comment]
@nergal-perm as a temporary solution, use this URL for webhook: `https://www.0pdd.com/hook/github` In the meantime, I will investigate why rehttp doesn't pass the payload through.

**Comment by nergal-perm** [comment]
@yegor256 , it's all the same, seems that problem is not in the rehttp service. 

![image](https://github.com/yegor256/0pdd/assets/4876699/b3edc627-d35e-404e-af43-f51d44e8018c)

![image](https://github.com/yegor256/0pdd/assets/4876699/b28f6d96-f962-4cee-8dd1-7cc713012a1f)

**Comment by pnatashap** [comment]
@nergal-perm workaround is to change content-type for webhook to application/json (and can return back rehttp). It will work in both cases, will check what happens with application/x-www-form-urlencoded message type, params are really not parsed

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#591](https://github.com/yegor256/0pdd/issues/591) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#591](https://github.com/yegor256/0pdd/issues/591) is solved here.
