### ISSUE TITLE
503 response

### ISSUE THREAD

**Issue by pchmielowski** [yegor256/0pdd#61]
After pushing a change to repo, 0pdd answers with:
```
Connection: keep-alive
Content-Length: 5266
Content-Type: text/html;charset=utf-8
Date: Thu, 06 Apr 2017 11:33:16 GMT
Server: WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)
Via: 1.1 vegur
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
```
```
<html>
  <head>
    <title>0pdd</title>
    <meta charset='UTF-8'>
    <meta content='width=device-width, initial-scale=1.0' name='viewport'>
    <meta content='PDD, GitHub, Puzzle Driven Development' name='keywords'>
    <meta content='Hosted PDD puzzles collector' name='description'>
    <link href='http://www.0pdd.com/css/main.css' rel='stylesheet' type='text/css'>
    <link href='https://avatars2.githubusercontent.com/u/24456188' rel='shortcut icon'>
  </head>
  <body>
    <p style='color: red;'>
      Internal error
    </p>
    <pre>uninitialized constant JobStarred
    	/app/0pdd.rb:165:in `block in <top (required)>'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
    	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
    	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
    	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'</pre>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-1963507-49', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@pchmielowski fixed already in https://github.com/yegor256/0pdd/commit/95007612ad99131cadefe8785fbde0b066270623 thanks
