### ISSUE TITLE
ResourceNotFoundException on every webhook invocation

### ISSUE THREAD

**Issue by nergal-perm** [yegor256/0pdd#673]
It seems that something is wrong on the AWS DynamoDB side, because each of the webhook invocations throws an error.

One of the commits that resulted in an error: https://github.com/nergal-perm/java-decita/commit/a377739996ad32b8713e66ce04e4988ebdf7f5b0

Stacktrace of the error:

```
Aws::DynamoDB::Errors::ResourceNotFoundException
Requested resource not found
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-dynamodb-1.102.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:119:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.191.1/lib/seahorse/client/request.rb:72:in `send_request'
/app/vendor/bundle/ruby/3.1.0/gems/aws-sdk-dynamodb-1.102.0/lib/aws-sdk-dynamodb/client.rb:4642:in `put_item'
/app/objects/log.rb:42:in `put'
/app/objects/storage/logged_storage.rb:36:in `save'
/app/objects/storage/versioned_storage.rb:44:in `save'
/app/objects/storage/cached_storage.rb:47:in `save'
/app/objects/storage/once_storage.rb:34:in `save'
/app/objects/storage/safe_storage.rb:37:in `save'
/app/objects/storage/upgraded_storage.rb:44:in `save'
/app/objects/storage/sync_storage.rb:35:in `block in save'
/app/objects/storage/sync_storage.rb:35:in `synchronize'
/app/objects/storage/sync_storage.rb:35:in `save'
/app/objects/puzzles.rb:56:in `save'
/app/objects/puzzles.rb:48:in `deploy'
/app/objects/jobs/job.rb:38:in `proceed'
/app/objects/jobs/job_starred.rb:32:in `proceed'
/app/objects/jobs/job_recorded.rb:31:in `proceed'
/app/objects/jobs/job_emailed.rb:33:in `proceed'
/app/objects/jobs/job_commiterrors.rb:33:in `proceed'
/app/objects/jobs/job_detached.rb:48:in `exclusive'
/app/objects/jobs/job_detached.rb:36:in `block in proceed'
/app/objects/jobs/job_detached.rb:36:in `fork'
/app/objects/jobs/job_detached.rb:36:in `proceed'
/app/0pdd.rb:549:in `process_request'
/app/0pdd.rb:380:in `block in <top (required)>'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `block in compile!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1089:in `route_eval'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1120:in `block in process_route'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `catch'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `process_route'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1069:in `block in route!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `route!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1190:in `block in dispatch!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1185:in `dispatch!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `block in call!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `call!'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:990:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/rewindable_input.rb:25:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/deflater.rb:47:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/xss_header.rb:20:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/path_traversal.rb:18:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/json_csrf.rb:28:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/base.rb:53:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/base.rb:53:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-4.0.0/lib/rack/protection/frame_options.rb:33:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/logger.rb:19:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/common_logger.rb:43:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:266:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:259:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/head.rb:15:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rack-3.0.9/lib/rack/method_override.rb:28:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:2115:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1674:in `block in call'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1890:in `synchronize'
/app/vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1674:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/rackup-2.1.0/lib/rackup/handler/webrick.rb:111:in `service'
/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

**Comment by blablatdinov** [comment]
@yegor256 take a look

**Comment by yegor256** [comment]
@nergal-perm my mistake. fixed already. thanks for reporting!
