### ISSUE TITLE
0pdd doesn't handle force pushes

### ISSUE THREAD

**Issue by extsoft** [yegor256/0pdd#72]
Repository - [https://github.com/extsoft/insight](https://github.com/extsoft/insight).

Steps to reproduce:
1. Push new commit
2. Amend (`git commit --amend`) and push again (`git push -f`)

Actual:
Email subject: ` [extsoft/insight] test 0pdd (23420d6)`
Body: 
```
I wasn't able to retrieve PDD puzzles from the code base (if you think that it's a bug on your our side, please submit it to yegor256/0pdd:

cd /tmp/0pdd/extsoft/insight && git reset --hard --quiet && git clean --force -d && git pull --quiet: 256 (not zero):
Auto-merging git/git-utils.bash
CONFLICT (add/add): Merge conflict in git/git-utils.bash
Automatic merge failed; fix conflicts and then commit the result.

/app/objects/exec.rb:38:in `run'
/app/objects/git_repo.rb:89:in `pull'
/app/objects/git_repo.rb:67:in `push'
/app/objects/job.rb:41:in `proceed'
/app/objects/job_starred.rb:35:in `proceed'
/app/objects/job_recorded.rb:33:in `proceed'
/app/objects/job_emailed.rb:36:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:51:in `block in exclusive'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
/app/objects/job_detached.rb:49:in `exclusive'
/app/objects/job_detached.rb:39:in `block in proceed'
/app/objects/job_detached.rb:39:in `fork'
/app/objects/job_detached.rb:39:in `proceed'
/app/0pdd.rb:201:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
—
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@extsoft thanks for reporting

**Comment by yegor256** [comment]
@extsoft reproduced in 	78d1bc9 and fixed in d65985f

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.7`

**Comment by yegor256** [comment]
@extsoft try it now, please.

**Comment by extsoft** [comment]
It still reproduces. Log: 
```
I wasn't able to retrieve PDD puzzles from the code base (if you think that it's a bug on your our side, please submit it to yegor256/0pdd:

cd /tmp/0pdd/extsoft/insight && git reset --hard --quiet && git clean --force -d && git fetch --quiet && git rebase --strategy-option=theirs origin/master: 256 (not zero):

It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "/tmp/0pdd/extsoft/insight/.git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

/app/objects/exec.rb:38:in `run'
/app/objects/git_repo.rb:90:in `pull'
/app/objects/git_repo.rb:67:in `push'
/app/objects/job.rb:41:in `proceed'
/app/objects/job_starred.rb:35:in `proceed'
/app/objects/job_recorded.rb:33:in `proceed'
/app/objects/job_emailed.rb:36:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:51:in `block in exclusive'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
/app/objects/job_detached.rb:49:in `exclusive'
/app/objects/job_detached.rb:39:in `block in proceed'
/app/objects/job_detached.rb:39:in `fork'
/app/objects/job_detached.rb:39:in `proceed'
/app/0pdd.rb:201:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_threa
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.8`

**Comment by yegor256** [comment]
@extsoft can you please try now?

**Comment by extsoft** [comment]
@yegor256 it still the same. Please consider to use `git reset origin/master --hard` to retrieve latest version of changes.

**Comment by yegor256** [comment]
@extsoft I'm doing it already: https://github.com/yegor256/0pdd/blob/0.16.8/objects/git_repo.rb#L87 :( I can't understand how to reproduce the problem you're having now in your repo. And it's different from what you reported originally. Let's close this ticket and report a new one, with the bug we're having now, please.

**Comment by extsoft** [comment]
Solved. @yegor256 thank you for support.

**Comment by yegor256** [comment]
@extsoft more in #76

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#72` was not in scope
