### ISSUE TITLE
puzzles.rb: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#87]
```
undefined method `[]' for nil:NilClass

/app/objects/puzzles.rb:117:in `block in covered'
/app/objects/puzzles.rb:113:in `each'
/app/objects/puzzles.rb:113:in `covered'
/app/objects/puzzles.rb:41:in `deploy'
/app/objects/job.rb:42:in `proceed'
/app/objects/job_starred.rb:35:in `proceed'
/app/objects/job_recorded.rb:33:in `proceed'
/app/objects/job_emailed.rb:36:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:51:in `block in exclusive'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.3`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#87` was not in scope
