### ISSUE TITLE
uninitialized constant GithubTickets::Truncate

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#95]
```
uninitialized constant GithubTickets::Truncate

/app/objects/github_tickets.rb:46:in `submit'
/app/objects/logged_tickets.rb:47:in `submit'
/app/objects/commit_tickets.rb:39:in `submit'
/app/objects/emailed_tickets.rb:37:in `submit'
/app/objects/puzzles.rb:86:in `block in submit'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/app/objects/puzzles.rb:86:in `map'
/app/objects/puzzles.rb:86:in `submit'
/app/objects/puzzles.rb:44:in `deploy'
/app/objects/job.rb:42:in `proceed'
/app/objects/job_starred.rb:35:in `proceed'
/app/objects/job_recorded.rb:33:in `proceed'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.7`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#95` was not in scope
